apiVersion: skaffold/v2alpha4
kind: Config

metadata:
  name: popular-slides

build:
  artifacts:
    - image: farberg/popular-slides-spark
      context: spark-app

    - image: web-app
      context: web-app

    - image: datagenerator-app
      context: datagenerator-app

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
