apiVersion: skaffold/v2beta15
kind: Config

metadata:
  name: popular-slides

build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: spark-popular-app
      context: spark-app

    - image: web-app
      context: web-app
      docker:
        dockerfile: Dockerfile

    - image: datagenerator-app
      context: datagenerator-app
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
