apiVersion: skaffold/v2beta15
kind: Config

metadata:
  name: popular-slides

build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: farberg/popular-slides-spark
      context: spark-app

    - image: web-app
      context: web-app
      docker:
        dockerfile: Dockerfile

    - image: datagenerator-app
      context: datagenerator-app
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml

portForward:
  - resourceType: deployment
    resourceName: web-app
    port: 5000
    localPort: 5000
  - resourceType: deployment
    resourceName: datagenerator-app
    port: 3000
    localPort: 3000
