#Begin: Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-deployment-init-configmap
data:
  mysql-init.sql: |

    CREATE TABLE `dishes` (
      `dish_id` char(36) NOT NULL,
      `dish_name` varchar(250) DEFAULT NULL,
      `dish_price` float DEFAULT NULL,
      PRIMARY KEY (`dish_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    CREATE TABLE `stores` (
      `store_id` char(36) NOT NULL,
      `store_name` varchar(250) DEFAULT NULL,
      `store_lat` varchar(20) DEFAULT NULL,
      `store_lon` varchar(20) DEFAULT NULL,
      PRIMARY KEY (`store_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    CREATE TABLE `orders` (
      `order_id` char(36) NOT NULL,
      `dish_id` char(36) DEFAULT NULL,
      `store_id` char(36) DEFAULT NULL,
      `timestamp` datetime DEFAULT NULL,
      PRIMARY KEY (`order_id`),
      KEY `orders_dish_id_fk` (`dish_id`),
      KEY `orders_store_id_fk` (`store_id`),
      CONSTRAINT `orders_dishes_id_fk` FOREIGN KEY (`dish_id`) REFERENCES `dishes` (`dish_id`),
      CONSTRAINT `orders_stores_id_fk` FOREIGN KEY (`store_id`) REFERENCES `stores` (`store_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    CREATE TABLE `popular_dish` (
      `dish_id` char(36) NOT NULL,
      `count` bigint DEFAULT NULL,
      PRIMARY KEY (`dish_id`),
      CONSTRAINT `popular_dish_dish_id_fk` FOREIGN KEY (`dish_id`) REFERENCES `dishes` (`dish_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    CREATE TABLE `popular_store` (
      `store_id` char(36) NOT NULL,
      `count` bigint DEFAULT NULL,
      PRIMARY KEY (`store_id`),
      CONSTRAINT `popular_store_store_id_fk` FOREIGN KEY (`store_id`) REFERENCES `stores` (`store_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    INSERT INTO dishes (dish_id, dish_name, dish_price) VALUES ('61579f07-ff46-4078-af3a-8228f0a294b7', 'Hackfleischröllchen mit Djuvec-Reis und Salat', '12.9');
    INSERT INTO dishes (dish_id, dish_name, dish_price) VALUES ('535bac21-27dd-4ed2-b28b-5c643556f4ba', 'Eisbein mit Sauerkraut, Salzkartoffeln und Erbspürree mit Speck', '13.89');
    INSERT INTO dishes (dish_id, dish_name, dish_price) VALUES ('38adb785-246b-4efe-94e9-d194fa8c4978', 'Meeresfrüchtesalat mit Chili und Thai-Kräutem', '11.50');
  
    INSERT INTO stores (store_id, store_name, store_lat, store_lon) VALUES ('61579f27-ff46-40a8-af3a-8228f0a294b7', 'Five Rivers Restaurant', '52.52168860493468', '13.384807813113612');
    INSERT INTO stores (store_id, store_name, store_lat, store_lon) VALUES ('61529f27-ff46-40a8-af3a-8228f0a294b7', 'Best Worscht', '52.510491388069475', '13.380505155941325');
    INSERT INTO stores (store_id, store_name, store_lat, store_lon) VALUES ('61529f21-ff46-40a8-af3a-8228f0a294b7', 'Restaurant Facil', '52.509029388326915', '13.373680166244354');
   
   #INSERT INTO stores (store_id, store_name, store_lat, store_lon) VALUES ('aaa', 'aaa', 22, 12);

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: my-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mysql
  template:
    metadata:
      labels:
        app: my-mysql
    spec:
      # Mount the configmap volume
      # This is an excerpt of deployment.spec.template.spec
      volumes:
        - name: init-volume
          configMap:
            name: mysql-deployment-init-configmap
      containers:
        - name: my-mysql
          image: mysql
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/
          # Set required environment variables to initialize the container
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysecretpw"
            - name: MYSQL_DATABASE
              value: "popular"
          ports:
            - containerPort: 33060
            - containerPort: 3306

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  name: my-app-mysql-service
spec:
  selector:
    app: my-mysql
  ports:
    - name: mysql-xproto
      protocol: TCP
      port: 33060
      targetPort: 33060
    - name: mysql-standard
      protocol: TCP
      port: 3306
      targetPort: 3306
#End: Service
